/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWorldIDRouter,
  IWorldIDRouterInterface,
} from "../../../contracts/interfaces/IWorldIDRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "groupId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "root",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "signalHash",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "nullifierHash",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "externalNullifierHash",
        type: "uint256",
      },
      {
        internalType: "uint256[8]",
        name: "proof",
        type: "uint256[8]",
      },
    ],
    name: "verifyProof",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWorldIDRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IWorldIDRouterInterface {
    return new utils.Interface(_abi) as IWorldIDRouterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWorldIDRouter {
    return new Contract(address, _abi, signerOrProvider) as IWorldIDRouter;
  }
}
