/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IUserRegistry,
  IUserRegistryInterface,
} from "../../contracts/IUserRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "userAddr",
        type: "address",
      },
    ],
    name: "isUserExist",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "worldCoinId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "userAddr",
        type: "address",
      },
    ],
    name: "registerUser",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IUserRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IUserRegistryInterface {
    return new utils.Interface(_abi) as IUserRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUserRegistry {
    return new Contract(address, _abi, signerOrProvider) as IUserRegistry;
  }
}
