/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "ERC7007",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC7007__factory>;
    getContractFactory(
      name: "IErc7007",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IErc7007__factory>;
    getContractFactory(
      name: "ISignUp",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISignUp__factory>;
    getContractFactory(
      name: "IWorldIDRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWorldIDRouter__factory>;
    getContractFactory(
      name: "IUserRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUserRegistry__factory>;
    getContractFactory(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVerifier__factory>;
    getContractFactory(
      name: "SignUp",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SignUp__factory>;
    getContractFactory(
      name: "UserRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UserRegistry__factory>;

    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721>;
    getContractAt(
      name: "IERC721Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Receiver>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "ERC7007",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC7007>;
    getContractAt(
      name: "IErc7007",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IErc7007>;
    getContractAt(
      name: "ISignUp",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ISignUp>;
    getContractAt(
      name: "IWorldIDRouter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IWorldIDRouter>;
    getContractAt(
      name: "IUserRegistry",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUserRegistry>;
    getContractAt(
      name: "IVerifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IVerifier>;
    getContractAt(
      name: "SignUp",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SignUp>;
    getContractAt(
      name: "UserRegistry",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UserRegistry>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
